[phases.setup]
nixPkgs = ["php82", "php82Packages.intl", "php82Packages.gd", "php82Packages.zip", "nodejs_20"]

[phases.build]
cmds = ["npm install && npm run build", "composer install --no-dev --optimize-autoloader"]